
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMS : IS '.'IS : I RIRI : RI : I RII : '[' NUM ';' NUM ']'"
    
_lr_action_items = {'[':([0,3,6,12,],[4,4,4,-5,]),'$end':([1,5,],[0,-1,]),'.':([2,3,6,7,9,12,],[5,-3,-3,-2,-4,-5,]),'NUM':([4,10,],[8,11,]),';':([8,],[10,]),']':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'IS':([0,],[2,]),'I':([0,3,6,],[3,6,6,]),'RI':([3,6,],[7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> IS .','S',2,'p_S','anaTeste2.py',28),
  ('IS -> I RI','IS',2,'p_IS','anaTeste2.py',32),
  ('RI -> <empty>','RI',0,'p_RI_empty','anaTeste2.py',36),
  ('RI -> I RI','RI',2,'p_RI_non_empty','anaTeste2.py',40),
  ('I -> [ NUM ; NUM ]','I',5,'p_I','anaTeste2.py',44),
]
