
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "PAL STRColecao : Tuples '.'Tuples : TupleTuples : Tuples TupleTuple : TId '(' Faces ')'Faces : FacetaFaces : Faces ',' FacetaFaceta : Field '=' ValueField : PALValue : STRTId : PAL"
    
_lr_action_items = {'PAL':([0,2,3,7,8,13,14,],[5,5,-2,-3,12,-4,12,]),'$end':([1,6,],[0,-1,]),'.':([2,3,7,13,],[6,-2,-3,-4,]),'(':([4,5,],[8,-10,]),')':([9,10,16,17,18,],[13,-5,-6,-7,-9,]),',':([9,10,16,17,18,],[14,-5,-6,-7,-9,]),'=':([11,12,],[15,-8,]),'STR':([15,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Colecao':([0,],[1,]),'Tuples':([0,],[2,]),'Tuple':([0,2,],[3,7,]),'TId':([0,2,],[4,4,]),'Faces':([8,],[9,]),'Faceta':([8,14,],[10,16,]),'Field':([8,14,],[11,11,]),'Value':([15,],[17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Colecao","S'",1,None,None,None),
  ('Colecao -> Tuples .','Colecao',2,'p_Colecao','yacc_teste.py',6),
  ('Tuples -> Tuple','Tuples',1,'p_Tuples1','yacc_teste.py',10),
  ('Tuples -> Tuples Tuple','Tuples',2,'p_Tuples2','yacc_teste.py',14),
  ('Tuple -> TId ( Faces )','Tuple',4,'p_Tuple','yacc_teste.py',18),
  ('Faces -> Faceta','Faces',1,'p_Faces1','yacc_teste.py',23),
  ('Faces -> Faces , Faceta','Faces',3,'p_Faces2','yacc_teste.py',27),
  ('Faceta -> Field = Value','Faceta',3,'p_Faceta','yacc_teste.py',31),
  ('Field -> PAL','Field',1,'p_Field','yacc_teste.py',35),
  ('Value -> STR','Value',1,'p_Value','yacc_teste.py',39),
  ('TId -> PAL','TId',1,'p_TId','yacc_teste.py',43),
]
