
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AREA CIRC ID LOSA NUM PERIMETRO QUAD RECT TRIA\n    Programa   : Frase\n               | Frase Programa\n    \n    Frase      : Declaracao\n               | Calculo\n    \n    Declaracao : Lista ':' Figura\n    \n    Figura     : Rectangulo\n               | Circulo\n               | Quadrado\n               | Triangulo\n               | Losango\n    \n    Rectangulo : RECT '(' NUM ',' NUM ')'\n    Circulo    : CIRC '(' NUM ')'\n    Quadrado   : QUAD '(' NUM ')'\n    Triangulo  : TRIA '(' NUM ',' NUM ')'\n    Losango    : LOSA '(' NUM ',' NUM ')'\n    \n    Calculo    : AREA '(' Lista ')'\n               | PERIMETRO '(' ID ')'\n    \n    Lista      : ID\n               | ID ',' Lista\n    "
    
_lr_action_items = {'AREA':([0,2,3,4,14,15,16,17,18,19,33,34,41,42,48,49,50,],[6,6,-3,-4,-5,-6,-7,-8,-9,-10,-16,-17,-12,-13,-11,-14,-15,]),'PERIMETRO':([0,2,3,4,14,15,16,17,18,19,33,34,41,42,48,49,50,],[7,7,-3,-4,-5,-6,-7,-8,-9,-10,-16,-17,-12,-13,-11,-14,-15,]),'ID':([0,2,3,4,11,12,13,14,15,16,17,18,19,33,34,41,42,48,49,50,],[8,8,-3,-4,8,26,8,-5,-6,-7,-8,-9,-10,-16,-17,-12,-13,-11,-14,-15,]),'$end':([1,2,3,4,9,14,15,16,17,18,19,33,34,41,42,48,49,50,],[0,-1,-3,-4,-2,-5,-6,-7,-8,-9,-10,-16,-17,-12,-13,-11,-14,-15,]),':':([5,8,27,],[10,-18,-19,]),'(':([6,7,20,21,22,23,24,],[11,12,28,29,30,31,32,]),')':([8,25,26,27,36,37,45,46,47,],[-18,33,34,-19,41,42,48,49,50,]),',':([8,35,38,39,],[13,40,43,44,]),'RECT':([10,],[20,]),'CIRC':([10,],[21,]),'QUAD':([10,],[22,]),'TRIA':([10,],[23,]),'LOSA':([10,],[24,]),'NUM':([28,29,30,31,32,40,43,44,],[35,36,37,38,39,45,46,47,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Programa':([0,2,],[1,9,]),'Frase':([0,2,],[2,2,]),'Declaracao':([0,2,],[3,3,]),'Calculo':([0,2,],[4,4,]),'Lista':([0,2,11,13,],[5,5,25,27,]),'Figura':([10,],[14,]),'Rectangulo':([10,],[15,]),'Circulo':([10,],[16,]),'Quadrado':([10,],[17,]),'Triangulo':([10,],[18,]),'Losango':([10,],[19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Programa","S'",1,None,None,None),
  ('Programa -> Frase','Programa',1,'p_grammar','ap_yacc.py',11),
  ('Programa -> Frase Programa','Programa',2,'p_grammar','ap_yacc.py',12),
  ('Frase -> Declaracao','Frase',1,'p_grammar','ap_yacc.py',14),
  ('Frase -> Calculo','Frase',1,'p_grammar','ap_yacc.py',15),
  ('Declaracao -> Lista : Figura','Declaracao',3,'p_decl','ap_yacc.py',21),
  ('Figura -> Rectangulo','Figura',1,'p_fig','ap_yacc.py',33),
  ('Figura -> Circulo','Figura',1,'p_fig','ap_yacc.py',34),
  ('Figura -> Quadrado','Figura',1,'p_fig','ap_yacc.py',35),
  ('Figura -> Triangulo','Figura',1,'p_fig','ap_yacc.py',36),
  ('Figura -> Losango','Figura',1,'p_fig','ap_yacc.py',37),
  ('Rectangulo -> RECT ( NUM , NUM )','Rectangulo',6,'p_fig_args','ap_yacc.py',44),
  ('Circulo -> CIRC ( NUM )','Circulo',4,'p_fig_args','ap_yacc.py',45),
  ('Quadrado -> QUAD ( NUM )','Quadrado',4,'p_fig_args','ap_yacc.py',46),
  ('Triangulo -> TRIA ( NUM , NUM )','Triangulo',6,'p_fig_args','ap_yacc.py',47),
  ('Losango -> LOSA ( NUM , NUM )','Losango',6,'p_fig_args','ap_yacc.py',48),
  ('Calculo -> AREA ( Lista )','Calculo',4,'p_calc','ap_yacc.py',59),
  ('Calculo -> PERIMETRO ( ID )','Calculo',4,'p_calc','ap_yacc.py',60),
  ('Lista -> ID','Lista',1,'p_list','ap_yacc.py',85),
  ('Lista -> ID , Lista','Lista',3,'p_list','ap_yacc.py',86),
]
